### PR TITLE
TPK Generator tool

### PR DESCRIPTION
**Pull request by apuder**
Please ignore the other commits. I haven't pushed them to master yet. I'd like some feedback on commit 'ada66b7'.

### CODE REVIEW

**Comment by cjkrieseSF** [comment]
I see the dependency but for some reason, it's still not compiling for me.  Just to confirm, you're running `./gradlew fatJar` from the tools/tpk subdirectory, right?

**Comment by apuder** [comment]
Yep, that should do it. Can you paste the console log here?

**Comment by cjkrieseSF** [comment]
The output without flags isn't very telling.
`/Users/cjkriese/dev/trs80/TRS-80/tools/tpk/src/main/java/org/puder/trs80/tpk/Util.java:11: error: cannot find symbol
import java.util.Base64;
                ^
  symbol:   class Base64
  location: package java.util
/Users/cjkriese/dev/trs80/TRS-80/tools/tpk/src/main/java/org/puder/trs80/tpk/Util.java:53: error: cannot find symbol
        return Base64.getDecoder().decode(b64.substring(i + 1));
               ^
  symbol:   variable Base64
  location: class Util
2 errors
:compileJava FAILED
`

When I run with --debug, there's copious output  but the relevant lines are...

`00:19:58.530 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Visiting dependency :tpk:unspecified(compile) -> commons-codec:commons-codec:1.9(dependency: commons-codec#commons-codec;1.9 {compile=[default]})
00:19:58.530 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Selecting new module version commons-codec:commons-codec:1.9
00:19:58.531 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainDependencyResolver] Attempting to resolve commons-codec:commons-codec:1.9 using repositories [BintrayJCenter]
00:19:58.531 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.IvyXmlModuleDescriptorParser] post 1.3 ivy file: using exact as default matcher
00:19:58.532 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'commons-codec:commons-codec:1.9' in 'BintrayJCenter'
00:19:58.532 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainDependencyResolver] Using commons-codec:commons-codec:1.9 from Maven repository 'BintrayJCenter'`

**Comment by apuder** [comment]
It seems I am using java.util.Base64 instead of org.apache.commons.codec.binary.Base64 in that file (Utils.java). Can you change the import and try again?

**Comment by apuder** [comment]
There is another change that is necessary in Util.java. I just pushed another commit to branch tpk. Try that.

**Comment by cjkrieseSF** [comment]
@apuder alll compiles now and I built a tpk and unzipped it. Looking good :+1:

**Comment by apuder** [comment]
Thanks! I'll close this PR, do some rebasing and then merge with master.

**Pull request closed without merging**
