### PR TITLE
Market prototype

### PR DESCRIPTION
**Pull request by cjkrieseSF**

### CODE REVIEW

**Comment by apuder** [comment]
Nice work!  What is the intent of the MarketDatabase class on the device? As a cache of the remote MarketDatabase instance? Should this be a proxy to query the remote server instead of being a local DBFlow DB?

**Comment by cjkrieseSF** [comment]
The `MarketDatabase` class is required for the DBFlow library and when compiled, the annotations result in a generated class called `Market$Database extends BaseDatabaseDefinition` which contains collections of models and their corresponding table classes.

**Comment by apuder** [comment]
I'm OK to merge WIP (the whole emulator is WIP after all). Just one request: I will probably do a couple of maintenance releases before we are ready to go public with the app store. Could you please add a runtime flag TRS80Application.ENABLE_APP_STORE that will disable the 'shopping cart' action bar icon? If you are a gradle master, perhaps create a separate product flavor.

**Comment by cjkrieseSF** [comment]
Sure, the flag is easy enough to do.  However, if you want to just wait until, it's more fully "baked' I'm OK with that too.

**Comment by apuder** [comment]
Probably better if you focus on what you want to do and we worry about integration/merge conflicts later. Work your magic...

**Pull request closed without merging**
